---
title: "gallery"
author: "Ben Best"
date: "February 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

[Screenshots of Shiny applications](https://github.com/wch/webshot#screenshots-of-shiny-applications)

Applications:
* [https://ecoquants.shinyapps.io/edna-vis/](https://ecoquants.shinyapps.io/edna-vis/)
* [New Tab](http://ohi-science.nceas.ucsb.edu/ohi-global)
```{r}
library(tidyverse)
library(webshot)

#w = 992
#h = 744
#w = 470
#h = 330
w = 940 ; h = 660
w = 1425; h = 576
w = 1600; h = 600
z = 1    # zoom
r = 100     # resize, percent -> 248 × 186 pixels; want 470×330
#d = 2      # delay, seconds
redo = T

apps = read_csv('apps.csv') %>%
  mutate(
    png = sprintf('images/app_%s_%dx%d_r%03d_z%g.png', short, w, h, r, z))

for (i in 1:nrow(apps)){ # i=3
  a = apps[i,]
  if ((!file.exists(a$png) | redo) & a$publish){
    switch(a$do,
    url_tmp = 
      webshot(a$url_tmp, a$png, zoom=z, delay=a$delay_secs, vwidth=w, vheight=h) %>%
        resize(paste0(r,'%')) %>%
        shrink(),
    url = 
      webshot(a$url_shiny, a$png, zoom=z, delay=a$delay_secs, vwidth=w, vheight=h) %>%
        resize(paste0(r,'%')) %>%
        shrink(),
    dir = 
      appshot(a$dir_shiny, a$png, zoom=z, delay=10, vwidth=w, vheight=h) %>%
        resize(paste0(r,'%')) %>%
        shrink())
  }
}
```


